version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:1-10.0
    volumes:
      - ".:/workspace:cached"
    command: sleep infinity
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: devcontainer_mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - "mongodb_:/data/db"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - "es_:/usr/share/elasticsearch/data"
    networks:
      - app-network

volumes:
  mongodb_:
  es_:

networks:
  app-network:
    driver: bridge