<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Alkampfer.Assistant.Interfaces/Alkampfer.Assistant.Interfaces.csproj" />
  </ItemGroup>

</Project>
